### ISSUE TITLE
It's not possible to change channels data bindings dynamically in app life cycle

### ISSUE THREAD

**Issue by jniechcial** [netguru/ember-pusher-guru#10]
In service `pusher-base.js` we define `channelsData` that stores information to which channels and events we should subscribe to Pusher. However, it's not possible to change that dynamically in application life cycle - e.g. between route transitions.

Change of `channelsData` should trigger subscription to new events and channels and unsubscription from channels and events that were deleted from this object.

**Comment by Blackening999** [comment]
https://github.com/netguru/ember-pusher-guru/pull/14
