### ISSUE TITLE
getOwner is not a function

### ISSUE THREAD

**Issue by joebartels** [netguru/ember-pusher-guru#5]
Trying to use with ember 1.13.12
https://github.com/netguru/ember-pusher-guru/blob/master/addon/services/pusher-base.js#L5

**Comment by jniechcial** [comment]
Thanks @joebartels, I will try to fix it tomorrow. I'll add `getOwner` polyfill there.

**Comment by jniechcial** [comment]
@joebartels I bumped addon to 1.0, should be working now. Please give me a sign and you can check out the code here #6

**Comment by jniechcial** [comment]
I assume it's done.

**Comment by joebartels** [comment]
@jniechcial yep :) all good with 1.0. thanks for taking care of!
