### ISSUE TITLE
Config option for cluster

### ISSUE THREAD

**Issue by duboff** [netguru/ember-pusher-guru#8]
If youa re using a non-standard [cluster](https://github.com/pusher/pusher-js#cluster-string), this add on does not work. It should be a trivial change but I have not yet had time to figure it out.

**Comment by duboff** [comment]
Would be even better to expose all of the config options that pusher has

**Comment by jniechcial** [comment]
Actually yes, we should expose all the config possible. I will find time for testing and development in next two weeks (probably this weekend), until then if you will have any spare time thanks in advance for any contributions :)

**Comment by jniechcial** [comment]
@duboff I merged this new config options to master. I won't release new version until I make sure in some real-life project that it works (I am not working with Pusher right now, will ask couple of my friends to try master branch). If you will have time to check it please give me a sign if it works or not :)

**Comment by duboff** [comment]
Thanks @jniechcial. I ended up having to build a simple Pusher service myself using the tutorial from their website but will try to give this a go at some point.
